name: hold_me_tight
channels:
  - pytorch
dependencies:
  - python=3.8.3
  - numpy=1.18.1
  - pytorch=1.5.0
  - torchvision=0.6.0
  - cudatoolkit=10.1
  - matplotlib=3.1.3
  - notebook
  - pip
  - pip:
      - torch-dct==0.1.5
